let data = {
  AFG: { fillKey: 2, name: 'Afghanistan', code: '004', flag: 'flags/afghanistan.svg' },
  ALA: { fillKey: 2, name: 'Åland Islands', code: '248', flag: 'flags/aland_islands.svg' },
  ALB: { fillKey: 2, name: 'Albania', code: '008', flag: 'flags/albania.svg' },
  DZA: { fillKey: 2, name: 'Algeria', code: '012', flag: 'flags/algeria.svg' },
  ASM: { fillKey: 2, name: 'American Samoa', code: '016', flag: 'flags/american_samoa.svg' },
  AND: { fillKey: 2, name: 'Andorra', code: '020', flag: 'flags/andorra.svg' },
  AGO: { fillKey: 2, name: 'Angola', code: '024', flag: 'flags/angola.svg' },
  AIA: { fillKey: 2, name: 'Anguilla', code: '660', flag: 'flags/anguilla.svg' },
  ATA: { fillKey: 2, name: 'Antarctica', code: '010' },
  ATG: { fillKey: 2, name: 'Antigua and Barbuda', code: '028', flag: 'flags/antigua_and_barbuda.svg' },
  ARG: { fillKey: 2, name: 'Argentina', code: '032', flag: 'flags/argentina.svg' },
  ARM: { fillKey: 2, name: 'Armenia', code: '051', flag: 'flags/armenia.svg' },
  ABW: { fillKey: 2, name: 'Aruba', code: '533', flag: 'flags/aruba.svg' },
  AUS: { fillKey: 2, name: 'Australia', code: '036', flag: 'flags/australia.svg' },
  AUT: { fillKey: 1, name: 'Austria', code: '040', flag: 'flags/austria.svg' },
  AZE: { fillKey: 2, name: 'Azerbaijan', code: '031', flag: 'flags/azerbaijan.svg' },
  BHS: { fillKey: 2, name: 'Bahamas', code: '044', flag: 'flags/bahamas.svg' },
  BHR: { fillKey: 2, name: 'Bahrain', code: '048', flag: 'flags/bahrain.svg' },
  BGD: { fillKey: 2, name: 'Bangladesh', code: '050', flag: 'flags/bangladesh.svg' },
  BRB: { fillKey: 2, name: 'Barbados', code: '052', flag: 'flags/barbados.svg' },
  BLR: { fillKey: 2, name: 'Belarus', code: '112', flag: 'flags/belarus.svg' },
  BEL: { fillKey: 1, name: 'Belgium', code: '056', flag: 'flags/belgium.svg' },
  BLZ: { fillKey: 1, name: 'Belize', code: '084', flag: 'flags/belize.svg' },
  BEN: { fillKey: 2, name: 'Benin', code: '204', flag: 'flags/benin.svg' },
  BMU: { fillKey: 2, name: 'Bermuda', code: '060', flag: 'flags/bermuda.svg' },
  BTN: { fillKey: 2, name: 'Bhutan', code: '064', flag: 'flags/bhutan.svg' },
  BOL: { fillKey: 2, name: 'Bolivia', code: '068', flag: 'flags/bolivia.svg' },
  BES: { fillKey: 2, name: 'Bonaire, Sint Eustatius and Saba', code: '535', flag: 'flags/bonaire.svg' },
  BIH: { fillKey: 1, name: 'Bosnia and Herzegovina', code: '070', flag: 'flags/bosnia_and_herzegovina.svg' },
  BWA: { fillKey: 2, name: 'Botswana', code: '072', flag: 'flags/botswana.svg' },
  BVT: { fillKey: 2, name: 'Bouvet Island', code: '074', flag: '' },
  BRA: { fillKey: 2, name: 'Brazil', code: '076', flag: 'flags/brazil.svg' },
  IOT: { fillKey: 2, name: 'British Indian Ocean Territory', code: '086', flag: 'flags/british_indian_ocean_territory.svg' },
  BRN: { fillKey: 2, name: 'Brunei', code: '096', flag: 'flags/brunei.svg' },
  BGR: { fillKey: 1, name: 'Bulgaria', code: '100', flag: 'flags/bulgaria.svg' },
  BFA: { fillKey: 2, name: 'Burkina Faso', code: '854', flag: 'flags/burkina_faso.svg' },
  BDI: { fillKey: 2, name: 'Burundi', code: '108', flag: 'flags/burundi.svg' },
  CPV: { fillKey: 2, name: 'Cabo Verde', code: '132', flag: 'flags/cape_verde.svg' },
  KHM: { fillKey: 2, name: 'Cambodia', code: '116', flag: 'flags/cambodia.svg' },
  CMR: { fillKey: 2, name: 'Cameroon', code: '120', flag: 'flags/cameroon.svg' },
  CAN: { fillKey: 1, name: 'Canada', code: '124', flag: 'flags/canada.svg' },
  CYM: { fillKey: 2, name: 'Cayman Islands', code: '136', flag: 'flags/cayman_islands.svg' },
  CAF: { fillKey: 2, name: 'Central African Republic', code: '140', flag: 'flags/central_african_republic.svg' },
  TCD: { fillKey: 2, name: 'Chad', code: '148', flag: 'flags/chad.svg' },
  CHL: { fillKey: 2, name: 'Chile', code: '152', flag: 'flags/chile.svg' },
  CHN: { fillKey: 1, name: 'China', code: '156', flag: 'flags/china.svg' },
  CXR: { fillKey: 2, name: 'Christmas Island', code: '162', flag: 'flags/christmas_island.svg' },
  CCK: { fillKey: 2, name: 'Cocos (Keeling) Islands', code: '166', flag: 'flags/cocos_islands.svg' },
  COL: { fillKey: 2, name: 'Colombia', code: '170', flag: 'flags/colombia.svg' },
  COM: { fillKey: 2, name: 'Comoros', code: '174', flag: 'flags/comoros.svg' },
  COG: { fillKey: 2, name: 'Congo', code: '178', flag: 'flags/congo.svg' },
  COD: { fillKey: 2, name: 'Democratic Republic of the Congo', code: '180', flag: 'flags/democratic_republic_of_the_congo.svg' },
  COK: { fillKey: 2, name: 'Cook Islands', code: '184', flag: 'flags/cook_islands.svg' },
  CRI: { fillKey: 2, name: 'Costa Rica', code: '188', flag: 'flags/costa_rica.svg' },
  CIV: { fillKey: 2, name: "Côte d'Ivoire", code: '384', flag: 'flags/ivory_coast.svg' },
  HRV: { fillKey: 1, name: 'Croatia', code: '191', flag: 'flags/croatia.svg' },
  CUB: { fillKey: 2, name: 'Cuba', code: '192', flag: 'flags/cuba.svg' },
  CUW: { fillKey: 2, name: 'Curaçao', code: '531', flag: 'flags/curacao.svg' },
  CYP: { fillKey: 2, name: 'Cyprus', code: '196', flag: 'flags/cyprus.svg' },
  CZE: { fillKey: 1, name: 'Czechia', code: '203', flag: 'flags/czech_republic.svg' },
  DNK: { fillKey: 2, name: 'Denmark', code: '208', flag: 'flags/denmark.svg' },
  DJI: { fillKey: 2, name: 'Djibouti', code: '262', flag: 'flags/djibouti.svg' },
  DMA: { fillKey: 2, name: 'Dominica', code: '212', flag: 'flags/dominica.svg' },
  DOM: { fillKey: 2, name: 'Dominican Republic', code: '214', flag: 'flags/dominican_republic.svg' },
  ECU: { fillKey: 1, name: 'Ecuador', code: '218', flag: 'flags/ecuador.svg' },
  EGY: { fillKey: 1, name: 'Egypt', code: '818', flag: 'flags/egypt.svg' },
  SLV: { fillKey: 2, name: 'El Salvador', code: '222', flag: 'flags/el_salvador.svg' },
  GNQ: { fillKey: 2, name: 'Equatorial Guinea', code: '226', flag: 'flags/equatorial_guinea.svg' },
  ERI: { fillKey: 2, name: 'Eritrea', code: '232', flag: 'flags/eritrea.svg' },
  EST: { fillKey: 2, name: 'Estonia', code: '233', flag: 'flags/estonia.svg' },
  SWZ: { fillKey: 2, name: 'Eswatini', code: '748', flag: 'flags/eswatini.svg' },
  ETH: { fillKey: 2, name: 'Ethiopia', code: '231', flag: 'flags/ethiopia.svg' },
  FLK: { fillKey: 2, name: 'Falkland Islands (Malvinas)', code: '238', flag: 'flags/falkland_islands.svg' },
  FRO: { fillKey: 2, name: 'Faroe Islands', code: '234', flag: 'flags/faroe_islands.svg' },
  FJI: { fillKey: 1, name: 'Fiji', code: '242', flag: 'flags/fiji.svg' },
  FIN: { fillKey: 2, name: 'Finland', code: '246', flag: 'flags/finland.svg' },
  FRA: { fillKey: 1, name: 'France', code: '250', flag: 'flags/france.svg' },
  GUF: { fillKey: 2, name: 'French Guiana', code: '254', flag: 'flags/french_guyana_coat_of_arms.svg' },
  PYF: { fillKey: 2, name: 'French Polynesia', code: '258', flag: 'flags/french_polynesia.svg' },
  ATF: { fillKey: 2, name: 'French Southern Territories', code: '260', flag: 'flags/french_southern_and_antarctic_lands.svg' },
  GAB: { fillKey: 2, name: 'Gabon', code: '266', flag: 'flags/gabon.svg' },
  GMB: { fillKey: 2, name: 'Gambia', code: '270', flag: 'flags/gambia.svg' },
  GEO: { fillKey: 2, name: 'Georgia', code: '268', flag: 'flags/georgia.svg' },
  DEU: { fillKey: 1, name: 'Germany', code: '276', flag: 'flags/germany.svg' },
  GHA: { fillKey: 2, name: 'Ghana', code: '288', flag: 'flags/ghana.svg' },
  GIB: { fillKey: 2, name: 'Gibraltar', code: '292', flag: 'flags/gibraltar.svg' },
  GRC: { fillKey: 1, name: 'Greece', code: '300', flag: 'flags/greece.svg' },
  GRL: { fillKey: 2, name: 'Greenland', code: '304', flag: 'flags/greenland.svg' },
  GRD: { fillKey: 2, name: 'Grenada', code: '308', flag: 'flags/grenada.svg' },
  GLP: { fillKey: 2, name: 'Guadeloupe', code: '312', flag: 'flags/guadaloupe.svg' },
  GUM: { fillKey: 2, name: 'Guam', code: '316', flag: 'flags/guam.svg' },
  GTM: { fillKey: 1, name: 'Guatemala', code: '320', flag: 'flags/guatemala.svg' },
  GGY: { fillKey: 2, name: 'Guernsey', code: '831', flag: 'flags/guernsey.svg' },
  GIN: { fillKey: 2, name: 'Guinea', code: '324', flag: 'flags/guinea.svg' },
  GNB: { fillKey: 2, name: 'Guinea-Bissau', code: '624', flag: 'flags/guinea-bissau.svg' },
  GUY: { fillKey: 2, name: 'Guyana', code: '328', flag: 'flags/guyana.svg' },
  HTI: { fillKey: 2, name: 'Haiti', code: '332', flag: 'flags/haiti.svg' },
  HMD: { fillKey: 2, name: 'Heard Island and McDonald Islands', code: '334' },
  VAT: { fillKey: 1, name: 'Holy See', code: '336', flag: 'flags/vatican_city.svg' },
  HND: { fillKey: 2, name: 'Honduras', code: '340', flag: 'flags/honduras.svg' },
  HKG: { fillKey: 2, name: 'Hong Kong', code: '344', flag: 'flags/hong_kong.svg' },
  HUN: { fillKey: 1, name: 'Hungary', code: '348', flag: 'flags/hungary.svg' },
  ISL: { fillKey: 2, name: 'Iceland', code: '352', flag: 'flags/iceland.svg' },
  IND: { fillKey: 1, name: 'India', code: '356', flag: 'flags/india.svg' },
  IDN: { fillKey: 1, name: 'Indonesia', code: '360', flag: 'flags/indonesia.svg' },
  IRN: { fillKey: 2, name: 'Iran', code: '364', flag: 'flags/iran.svg' },
  IRQ: { fillKey: 2, name: 'Iraq', code: '368', flag: 'flags/iraq.svg' },
  IRL: { fillKey: 2, name: 'Ireland', code: '372', flag: 'flags/ireland.svg' },
  IMN: { fillKey: 2, name: 'Isle of Man', code: '833', flag: 'flags/isle_of_man.svg' },
  ISR: { fillKey: 2, name: 'Israel', code: '376', flag: 'flags/israel.svg' },
  ITA: { fillKey: 1, name: 'Italy', code: '380', flag: 'flags/italy.svg' },
  JAM: { fillKey: 2, name: 'Jamaica', code: '388', flag: 'flags/jamaica.svg' },
  JPN: { fillKey: 1, name: 'Japan', code: '392', flag: 'flags/japan.svg' },
  JEY: { fillKey: 2, name: 'Jersey', code: '832', flag: 'flags/jersey.svg' },
  JOR: { fillKey: 2, name: 'Jordan', code: '400', flag: 'flags/jordan.svg' },
  KAZ: { fillKey: 2, name: 'Kazakhstan', code: '398', flag: 'flags/kazakhstan.svg' },
  KEN: { fillKey: 2, name: 'Kenya', code: '404', flag: 'flags/kenya.svg' },
  KIR: { fillKey: 2, name: 'Kiribati', code: '296', flag: 'flags/kiribati.svg' },
  PRK: { fillKey: 2, name: "Democratic People's Republic of Korea", code: '408', flag: 'flags/north_korea.svg' },
  KOR: { fillKey: 2, name: 'Republic of Korea', code: '410', flag: 'flags/south_korea.svg' },
  KWT: { fillKey: 1, name: 'Kuwait', code: '414', flag: 'flags/kuwait.svg' },
  KGZ: { fillKey: 2, name: 'Kyrgyzstan', code: '417', flag: 'flags/kyrgyzstan.svg' },
  LAO: { fillKey: 1, name: "People's Democratic Republic of Lao", code: '418', flag: 'flags/laos.svg' },
  LVA: { fillKey: 2, name: 'Latvia', code: '428', flag: 'flags/latvia.svg' },
  LBN: { fillKey: 2, name: 'Lebanon', code: '422', flag: 'flags/lebanon.svg' },
  LSO: { fillKey: 2, name: 'Lesotho', code: '426', flag: 'flags/lesotho.svg' },
  LBR: { fillKey: 2, name: 'Liberia', code: '430', flag: 'flags/liberia.svg' },
  LBY: { fillKey: 2, name: 'Libya', code: '434', flag: 'flags/libya.svg' },
  LIE: { fillKey: 2, name: 'Liechtenstein', code: '438', flag: 'flags/liechtenstein.svg' },
  LTU: { fillKey: 2, name: 'Lithuania', code: '440', flag: 'flags/lithuania.svg' },
  LUX: { fillKey: 1, name: 'Luxembourg', code: '442', flag: 'flags/luxembourg.svg' },
  MAC: { fillKey: 2, name: 'Macao', code: '446', flag: 'flags/macao.svg' },
  MDG: { fillKey: 2, name: 'Madagascar', code: '450', flag: 'flags/madagascar.svg' },
  MWI: { fillKey: 2, name: 'Malawi', code: '454', flag: 'flags/malawi.svg' },
  MYS: { fillKey: 2, name: 'Malaysia', code: '458', flag: 'flags/malaysia.svg' },
  MDV: { fillKey: 2, name: 'Maldives', code: '462', flag: 'flags/maldives.svg' },
  MLI: { fillKey: 2, name: 'Mali', code: '466', flag: 'flags/mali.svg' },
  MLT: { fillKey: 2, name: 'Malta', code: '470', flag: 'flags/malta.svg' },
  MHL: { fillKey: 2, name: 'Marshall Islands', code: '584', flag: 'flags/marshall_islands.svg' },
  MTQ: { fillKey: 2, name: 'Martinique', code: '474', flag: 'flags/martinique.svg' },
  MRT: { fillKey: 2, name: 'Mauritania', code: '478', flag: 'flags/mauritania.svg' },
  MUS: { fillKey: 2, name: 'Mauritius', code: '480', flag: 'flags/mauritius.svg' },
  MYT: { fillKey: 2, name: 'Mayotte', code: '175', flag: 'flags/mayotte.svg' },
  MEX: { fillKey: 1, name: 'Mexico', code: '484', flag: 'flags/mexico.svg' },
  FSM: { fillKey: 2, name: 'Federated States of Micronesia', code: '583', flag: 'flags/federated_states_of_micronesia.svg' },
  MDA: { fillKey: 1, name: 'Republic of Moldova', code: '498', flag: 'flags/moldova.svg' },
  MCO: { fillKey: 1, name: 'Monaco', code: '492', flag: 'flags/monaco.svg' },
  MNG: { fillKey: 2, name: 'Mongolia', code: '496', flag: 'flags/mongolia.svg' },
  MNE: { fillKey: 1, name: 'Montenegro', code: '499', flag: 'flags/montenegro.svg' },
  MSR: { fillKey: 2, name: 'Montserrat', code: '500', flag: 'flags/montserrat.svg' },
  MAR: { fillKey: 1, name: 'Morocco', code: '504', flag: 'flags/morocco.svg' },
  MOZ: { fillKey: 2, name: 'Mozambique', code: '508', flag: 'flags/mozambique.svg' },
  MMR: { fillKey: 1, name: 'Myanmar', code: '104', flag: 'flags/myanmar.svg' },
  NAM: { fillKey: 2, name: 'Namibia', code: '516', flag: 'flags/namibia.svg' },
  NRU: { fillKey: 2, name: 'Nauru', code: '520', flag: 'flags/nauru.svg' },
  NPL: { fillKey: 1, name: 'Nepal', code: '524', flag: 'flags/nepal.svg' },
  NLD: { fillKey: 1, name: 'Netherlands', code: '528', flag: 'flags/netherlands.svg' },
  NCL: { fillKey: 2, name: 'New Caledonia', code: '540', flag: 'flags/new_caledonia.svg' },
  NZL: { fillKey: 2, name: 'New Zealand', code: '554', flag: 'flags/new_zealand.svg' },
  NIC: { fillKey: 2, name: 'Nicaragua', code: '558', flag: 'flags/nicaragua.svg' },
  NER: { fillKey: 2, name: 'Niger', code: '562', flag: 'flags/niger.svg' },
  NGA: { fillKey: 2, name: 'Nigeria', code: '566', flag: 'flags/nigeria.svg' },
  NIU: { fillKey: 2, name: 'Niue', code: '570', flag: 'flags/niue.svg' },
  NFK: { fillKey: 2, name: 'Norfolk Island', code: '574', flag: 'flags/norfolk_island.svg' },
  MKD: { fillKey: 2, name: 'North Macedonia', code: '807', flag: 'flags/north_macedonia.svg' },
  MNP: { fillKey: 2, name: 'Northern Mariana Islands', code: '580', flag: 'flags/northern_mariana_islands.svg' },
  NOR: { fillKey: 2, name: 'Norway', code: '578', flag: 'flags/norway.svg' },
  OMN: { fillKey: 2, name: 'Oman', code: '512', flag: 'flags/oman.svg' },
  PAK: { fillKey: 2, name: 'Pakistan', code: '586', flag: 'flags/pakistan.svg' },
  PLW: { fillKey: 2, name: 'Palau', code: '585', flag: 'flags/palau.svg' },
  PSE: { fillKey: 2, name: 'State of Palestine', code: '275', flag: 'flags/palestine.svg' },
  PAN: { fillKey: 2, name: 'Panama', code: '591', flag: 'flags/panama.svg' },
  PNG: { fillKey: 2, name: 'Papua New Guinea', code: '598', flag: 'flags/papua_new_guinea.svg' },
  PRY: { fillKey: 2, name: 'Paraguay', code: '600', flag: 'flags/paraguay.svg' },
  PER: { fillKey: 2, name: 'Peru', code: '604', flag: 'flags/peru.svg' },
  PHL: { fillKey: 2, name: 'Philippines', code: '608', flag: 'flags/philippines.svg' },
  PCN: { fillKey: 2, name: 'Pitcairn', code: '612', flag: 'flags/pitcairn_islands.svg' },
  POL: { fillKey: 1, name: 'Poland', code: '616', flag: 'flags/poland.svg' },
  PRT: { fillKey: 1, name: 'Portugal', code: '620', flag: 'flags/portugal.svg' },
  PRI: { fillKey: 2, name: 'Puerto Rico', code: '630', flag: 'flags/puerto_rico.svg' },
  QAT: { fillKey: 2, name: 'Qatar', code: '634', flag: 'flags/qatar.svg' },
  REU: { fillKey: 2, name: 'Réunion', code: '638', flag: 'flags/reunion.svg' },
  ROU: { fillKey: 1, name: 'Romania', code: '642', flag: 'flags/romania.svg' },
  RUS: { fillKey: 2, name: 'Russian Federation', code: '643', flag: 'flags/russia.svg' },
  RWA: { fillKey: 2, name: 'Rwanda', code: '646', flag: 'flags/rwanda.svg' },
  BLM: { fillKey: 2, name: 'Saint Barthélemy', code: '652', flag: 'flags/saint_barthelemy.svg' },
  SHN: { fillKey: 2, name: 'Saint Helena, Ascension and Tristan da Cunha', code: '654', flag: 'flags/saint_helena.svg' },
  KNA: { fillKey: 2, name: 'Saint Kitts and Nevis', code: '659', flag: 'flags/saint_kitts_and_nevis.svg' },
  LCA: { fillKey: 2, name: 'Saint Lucia', code: '662', flag: 'flags/saint_lucia.svg' },
  MAF: { fillKey: 2, name: 'Saint Martin (French part)', code: '663', flag: 'flags/saint_martin.svg' },
  SPM: { fillKey: 2, name: 'Saint Pierre and Miquelon', code: '666', flag: 'flags/saint_pierre.svg' },
  VCT: { fillKey: 2, name: 'Saint Vincent and the Grenadines', code: '670', flag: 'flags/saint_vincent_and_the_grenadines.svg' },
  WSM: { fillKey: 2, name: 'Samoa', code: '882', flag: 'flags/samoa.svg' },
  SMR: { fillKey: 2, name: 'San Marino', code: '674', flag: 'flags/san_marino.svg' },
  STP: { fillKey: 2, name: 'Sao Tome and Principe', code: '678', flag: 'flags/sao_tome_and_principe.svg' },
  SAU: { fillKey: 2, name: 'Saudi Arabia', code: '682', flag: 'flags/saudi_arabia.svg' },
  SEN: { fillKey: 2, name: 'Senegal', code: '686', flag: 'flags/senegal.svg' },
  SRB: { fillKey: 2, name: 'Serbia', code: '688', flag: 'flags/serbia.svg' },
  SYC: { fillKey: 2, name: 'Seychelles', code: '690', flag: 'flags/seychelles.svg' },
  SLE: { fillKey: 2, name: 'Sierra Leone', code: '694', flag: 'flags/sierra_leone.svg' },
  SGP: { fillKey: 1, name: 'Singapore', code: '702', flag: 'flags/singapore.svg' },
  SXM: { fillKey: 2, name: 'Sint Maarten (Dutch part)', code: '534', flag: 'flags/sint_maarten.svg' },
  SVK: { fillKey: 1, name: 'Slovakia', code: '703', flag: 'flags/slovakia.svg' },
  SVN: { fillKey: 2, name: 'Slovenia', code: '705', flag: 'flags/slovenia.svg' },
  SLB: { fillKey: 2, name: 'Solomon Islands', code: '090', flag: 'flags/solomon_islands.svg' },
  SOM: { fillKey: 2, name: 'Somalia', code: '706', flag: 'flags/somalia.svg' },
  ZAF: { fillKey: 2, name: 'South Africa', code: '710', flag: 'flags/south_africa.svg' },
  SGS: { fillKey: 2, name: 'South Georgia and the South Sandwich Islands', code: '239', flag: 'flags/south_georgia_and_the_south_sandwich_islands.svg' },
  SSD: { fillKey: 2, name: 'South Sudan', code: '728', flag: 'flags/south_sudan.svg' },
  ESP: { fillKey: 1, name: 'Spain', code: '724', flag: 'flags/spain.svg' },
  LKA: { fillKey: 2, name: 'Sri Lanka', code: '144', flag: 'flags/sri_lanka.svg' },
  SDN: { fillKey: 2, name: 'Sudan', code: '729', flag: 'flags/sudan.svg' },
  SUR: { fillKey: 2, name: 'Suriname', code: '740', flag: 'flags/suriname.svg' },
  SJM: { fillKey: 2, name: 'Svalbard and Jan Mayen', code: '744', flag: 'flags/svalbard_and_jan_mayen.svg' },
  SWE: { fillKey: 1, name: 'Sweden', code: '752', flag: 'flags/sweden.svg' },
  CHE: { fillKey: 2, name: 'Switzerland', code: '756', flag: 'flags/switzerland.svg' },
  SYR: { fillKey: 2, name: 'Syrian Arab Republic', code: '760', flag: 'flags/syria.svg' },
  TWN: { fillKey: 2, name: 'Taiwan, Province of China', code: '158', flag: 'flags/taiwan.svg' },
  TJK: { fillKey: 2, name: 'Tajikistan', code: '762', flag: 'flags/tajikistan.svg' },
  TZA: { fillKey: 2, name: 'Tanzania, United Republic of', code: '834', flag: 'flags/tanzania.svg' },
  THA: { fillKey: 1, name: 'Thailand', code: '764', flag: 'flags/thailand.svg' },
  TLS: { fillKey: 2, name: 'Timor-Leste', code: '626', flag: 'flags/timor_leste.svg' },
  TGO: { fillKey: 2, name: 'Togo', code: '768', flag: 'flags/togo.svg' },
  TKL: { fillKey: 2, name: 'Tokelau', code: '772', flag: 'flags/tokelau.svg' },
  TON: { fillKey: 2, name: 'Tonga', code: '776', flag: 'flags/tonga.svg' },
  TTO: { fillKey: 2, name: 'Trinidad and Tobago', code: '780', flag: 'flags/trinidad_and_tobago.svg' },
  TUN: { fillKey: 2, name: 'Tunisia', code: '788', flag: 'flags/tunisia.svg' },
  TUR: { fillKey: 1, name: 'Turkey', code: '792', flag: 'flags/turkey.svg' },
  TKM: { fillKey: 2, name: 'Turkmenistan', code: '795', flag: 'flags/turkmenistan.svg' },
  TCA: { fillKey: 2, name: 'Turks and Caicos Islands', code: '796', flag: 'flags/turks_and_caicos_islands.svg' },
  TUV: { fillKey: 2, name: 'Tuvalu', code: '798', flag: 'flags/tuvalu.svg' },
  UGA: { fillKey: 2, name: 'Uganda', code: '800', flag: 'flags/uganda.svg' },
  UKR: { fillKey: 1, name: 'Ukraine', code: '804', flag: 'flags/ukraine.svg' },
  ARE: { fillKey: 2, name: 'United Arab Emirates', code: '784', flag: 'flags/united_arab_emirates.svg' },
  GBR: { fillKey: 1, name: 'United Kingdom of Great Britain and Northern Ireland', code: '826', flag: 'flags/united_kingdom.svg' },
  USA: { fillKey: 1, name: 'United States of America', code: '840', flag: 'flags/united_states.svg' },
  UMI: { fillKey: 2, name: 'United States Minor Outlying Islands', code: '581', flag: 'flags/united_states.svg' },
  URY: { fillKey: 2, name: 'Uruguay', code: '858', flag: 'flags/uruguay.svg' },
  UZB: { fillKey: 2, name: 'Uzbekistan', code: '860', flag: 'flags/uzbekistan.svg' },
  VUT: { fillKey: 2, name: 'Vanuatu', code: '548', flag: 'flags/vanuatu.svg' },
  VEN: { fillKey: 2, name: 'Venezuela (Bolivarian Republic of)', code: '862', flag: 'flags/venezuela.svg' },
  VNM: { fillKey: 1, name: 'Vietnam', code: '704', flag: 'flags/vietnam.svg' },
  VGB: { fillKey: 2, name: 'Virgin Islands (British)', code: '092', flag: 'flags/british_virgin_islands.svg' },
  VIR: { fillKey: 2, name: 'Virgin Islands (U.S.)', code: '850', flag: 'flags/united_states_virgin_islands.svg' },
  WLF: { fillKey: 2, name: 'Wallis and Futuna', code: '876', flag: 'flags/wallis_and_futuna.svg' },
  ESH: { fillKey: 2, name: 'Western Sahara', code: '732', flag: 'flags/sahrawi_arab_democratic_republic.svg' },
  YEM: { fillKey: 2, name: 'Yemen', code: '887', flag: 'flags/yemen.svg' },
  ZMB: { fillKey: 2, name: 'Zambia', code: '894', flag: 'flags/zambia.svg' },
  ZWE: { fillKey: 2, name: 'Zimbabwe', code: '716', flag: 'flags/zimbabwe.svg' },
};
